"""
tests/test_report_generator.py
--------------------------------
Tests for Phase 5: report generator and CLI argument parser.

Run with:  python -m unittest tests.test_report_generator -v
"""

import sys, os, re, json, tempfile
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import unittest
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

from core.ingestion import load_model_input
from core.report import Finding, DiagnosisReport, Severity
from core.correlation_engine import run_diagnosis
from core.report_generator import render_report, save_report, print_report


# ── Helpers ───────────────────────────────────────────────────────────────────

def _strip_ansi(text: str) -> str:
    """Remove ANSI escape codes to compare plain content."""
    return re.sub(r"\033\[[0-9;]*m", "", text)


def _make_report(domain="healthcare", overfit=True, imbalance=True) -> DiagnosisReport:
    rng = np.random.default_rng(7)
    n   = 400
    y   = pd.Series([0] * 360 + [1] * 40 if imbalance else [0, 1] * 200)
    X   = pd.DataFrame(rng.standard_normal((n, 5)),
                       columns=[f"f{i}" for i in range(5)])
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.25, random_state=0,
        stratify=y if imbalance else None,
    )
    if overfit:
        model = DecisionTreeClassifier(max_depth=None, random_state=0)
    else:
        model = LogisticRegression(max_iter=500, class_weight="balanced")
    model.fit(X_train, y_train)
    mi = load_model_input(model, X_train, X_test, y_train, y_test,
                          task_type="classification", domain=domain)
    return run_diagnosis(mi)


def _clean_report() -> DiagnosisReport:
    """Report with no findings."""
    return DiagnosisReport(
        model_name="TestModel",
        task_type="classification",
        domain="general",
        overall_health_score=100,
        findings=[],
        interaction_warnings=[],
        recommended_action_sequence=[],
    )


# ── Test 1: render_report output structure ────────────────────────────────────

class TestRenderReport(unittest.TestCase):

    def setUp(self):
        self.report = _make_report()
        self.rendered = _strip_ansi(render_report(self.report))

    def test_contains_header_title(self):
        self.assertIn("ML FAILURE INTELLIGENCE REPORT", self.rendered)

    def test_contains_model_name(self):
        self.assertIn(self.report.model_name, self.rendered)

    def test_contains_domain(self):
        self.assertIn(self.report.domain, self.rendered)

    def test_contains_task_type(self):
        self.assertIn(self.report.task_type, self.rendered)

    def test_contains_health_score(self):
        score_str = f"{self.report.overall_health_score}/100"
        self.assertIn(score_str, self.rendered)

    def test_contains_findings_section(self):
        self.assertIn("FINDINGS", self.rendered)

    def test_contains_action_sequence(self):
        self.assertIn("RECOMMENDED ACTION SEQUENCE", self.rendered)

    def test_contains_footer(self):
        self.assertIn("Generated by MLFIE", self.rendered)

    def test_each_finding_id_appears(self):
        for finding in self.report.findings:
            self.assertIn(finding.id, self.rendered)

    def test_each_finding_severity_appears(self):
        for finding in self.report.findings:
            self.assertIn(finding.severity.value, self.rendered)

    def test_interaction_warnings_section_present_when_warnings_exist(self):
        if self.report.interaction_warnings:
            self.assertIn("INTERACTION WARNINGS", self.rendered)

    def test_no_findings_renders_healthy_message(self):
        report   = _clean_report()
        rendered = _strip_ansi(render_report(report))
        self.assertIn("No failures detected", rendered)

    def test_render_is_string(self):
        self.assertIsInstance(render_report(self.report), str)

    def test_render_does_not_raise_on_any_domain(self):
        for domain in ["general", "healthcare", "finance", "nlp"]:
            report = _make_report(domain=domain)
            try:
                _strip_ansi(render_report(report))
            except Exception as e:
                self.fail(f"render_report raised on domain={domain}: {e}")


# ── Test 2: save_report ───────────────────────────────────────────────────────

class TestSaveReport(unittest.TestCase):

    def setUp(self):
        self.report  = _make_report()
        self.tmp_dir = tempfile.mkdtemp()

    def test_json_file_created(self):
        path = os.path.join(self.tmp_dir, "report.json")
        result = save_report(self.report, path)
        self.assertTrue(os.path.exists(path))
        self.assertIn("json_path", result)

    def test_json_is_valid(self):
        path = os.path.join(self.tmp_dir, "report.json")
        save_report(self.report, path)
        with open(path) as f:
            data = json.load(f)
        self.assertIsInstance(data, dict)

    def test_json_contains_required_keys(self):
        path = os.path.join(self.tmp_dir, "report.json")
        save_report(self.report, path)
        with open(path) as f:
            data = json.load(f)
        for key in ["model_name", "task_type", "domain",
                    "overall_health_score", "findings",
                    "interaction_warnings", "recommended_action_sequence",
                    "generated_at", "mlfie_version"]:
            self.assertIn(key, data, f"Missing key: {key}")

    def test_json_findings_is_list(self):
        path = os.path.join(self.tmp_dir, "report.json")
        save_report(self.report, path)
        with open(path) as f:
            data = json.load(f)
        self.assertIsInstance(data["findings"], list)

    def test_json_finding_has_required_fields(self):
        path = os.path.join(self.tmp_dir, "report.json")
        save_report(self.report, path)
        with open(path) as f:
            data = json.load(f)
        if data["findings"]:
            finding = data["findings"][0]
            for field in ["id", "name", "severity", "evidence",
                          "explanation", "fix", "confidence"]:
                self.assertIn(field, finding)

    def test_text_file_created_when_flag_true(self):
        path = os.path.join(self.tmp_dir, "report.json")
        result = save_report(self.report, path, also_save_text=True)
        self.assertIn("text_path", result)
        self.assertTrue(os.path.exists(result["text_path"]))

    def test_text_file_not_created_when_flag_false(self):
        path = os.path.join(self.tmp_dir, "report2.json")
        result = save_report(self.report, path, also_save_text=False)
        self.assertNotIn("text_path", result)

    def test_text_file_has_no_ansi_codes(self):
        path = os.path.join(self.tmp_dir, "report.json")
        result = save_report(self.report, path, also_save_text=True)
        with open(result["text_path"], encoding="utf-8") as f:
            content = f.read()
        self.assertNotIn("\033[", content)

    def test_output_directory_created_if_missing(self):
        nested = os.path.join(self.tmp_dir, "nested", "dir", "report.json")
        save_report(self.report, nested)
        self.assertTrue(os.path.exists(nested))

    def test_clean_report_saves_without_error(self):
        path = os.path.join(self.tmp_dir, "clean.json")
        try:
            save_report(_clean_report(), path)
        except Exception as e:
            self.fail(f"save_report raised on clean report: {e}")


# ── Test 3: print_report ──────────────────────────────────────────────────────

class TestPrintReport(unittest.TestCase):

    def test_print_does_not_raise(self):
        """print_report() must not raise for any valid report."""
        report = _make_report()
        try:
            import io
            old_stdout = sys.stdout
            sys.stdout = io.StringIO()
            print_report(report)
            sys.stdout = old_stdout
        except Exception as e:
            sys.stdout = old_stdout
            self.fail(f"print_report raised: {e}")


# ── Test 4: CLI argument parser ───────────────────────────────────────────────

class TestCLIParser(unittest.TestCase):

    def setUp(self):
        sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
        from main import build_parser
        self.parser = build_parser()

    def test_demo_command_parses(self):
        args = self.parser.parse_args(["demo"])
        self.assertEqual(args.command, "demo")
        self.assertEqual(args.domain, "healthcare")  # default

    def test_demo_with_domain_parses(self):
        args = self.parser.parse_args(["demo", "--domain", "finance"])
        self.assertEqual(args.domain, "finance")

    def test_demo_with_output_parses(self):
        args = self.parser.parse_args(["demo", "--output", "out.json"])
        self.assertEqual(args.output, "out.json")

    def test_list_domains_command_parses(self):
        args = self.parser.parse_args(["list-domains"])
        self.assertEqual(args.command, "list-domains")

    def test_diagnose_requires_model(self):
        with self.assertRaises(SystemExit):
            self.parser.parse_args([
                "diagnose",
                "--train", "t.csv", "--test", "t.csv", "--target", "y"
            ])

    def test_diagnose_requires_train(self):
        with self.assertRaises(SystemExit):
            self.parser.parse_args([
                "diagnose",
                "--model", "m.pkl", "--test", "t.csv", "--target", "y"
            ])

    def test_diagnose_default_task_is_classification(self):
        args = self.parser.parse_args([
            "diagnose",
            "--model", "m.pkl", "--train", "t.csv",
            "--test", "t.csv", "--target", "y"
        ])
        self.assertEqual(args.task, "classification")

    def test_diagnose_default_domain_is_general(self):
        args = self.parser.parse_args([
            "diagnose",
            "--model", "m.pkl", "--train", "t.csv",
            "--test", "t.csv", "--target", "y"
        ])
        self.assertEqual(args.domain, "general")

    def test_diagnose_interactive_flag(self):
        args = self.parser.parse_args([
            "diagnose",
            "--model", "m.pkl", "--train", "t.csv",
            "--test", "t.csv", "--target", "y", "--interactive"
        ])
        self.assertTrue(args.interactive)

    def test_invalid_domain_rejected(self):
        with self.assertRaises(SystemExit):
            self.parser.parse_args([
                "diagnose",
                "--model", "m.pkl", "--train", "t.csv",
                "--test", "t.csv", "--target", "y",
                "--domain", "sports"
            ])

    def test_invalid_task_rejected(self):
        with self.assertRaises(SystemExit):
            self.parser.parse_args([
                "diagnose",
                "--model", "m.pkl", "--train", "t.csv",
                "--test", "t.csv", "--target", "y",
                "--task", "clustering"
            ])

    def test_no_command_exits(self):
        with self.assertRaises(SystemExit):
            self.parser.parse_args([])


# ── Test 5: CLI demo command end-to-end ───────────────────────────────────────

class TestCLIDemoEndToEnd(unittest.TestCase):

    def test_demo_runs_and_produces_json(self):
        """Run cmd_demo via argparse and verify JSON output is saved."""
        from main import build_parser, cmd_demo
        tmp = tempfile.mkdtemp()
        out = os.path.join(tmp, "demo_report.json")
        args = build_parser().parse_args(
            ["demo", "--domain", "finance", "--output", out]
        )
        cmd_demo(args)
        self.assertTrue(os.path.exists(out))
        with open(out) as f:
            data = json.load(f)
        self.assertIn("model_name", data)
        self.assertIn("findings", data)

    def test_list_domains_runs(self):
        """cmd_list_domains should not raise."""
        from main import build_parser, cmd_list_domains
        import io
        args = build_parser().parse_args(["list-domains"])
        old_stdout = sys.stdout
        sys.stdout = io.StringIO()
        try:
            cmd_list_domains(args)
        finally:
            sys.stdout = old_stdout


if __name__ == "__main__":
    unittest.main(verbosity=2)